"""empty message

Revision ID: 2227fe518d2d
Revises: 
Create Date: 2020-04-28 18:30:33.297197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2227fe518d2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.Column('e_titulo', sa.String(length=100), nullable=False),
    sa.Column('e_cuerpo', sa.String(length=500), nullable=False),
    sa.Column('e_imagen', sa.String(length=250), nullable=True),
    sa.Column('e_fecha', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('c_cuerpo', sa.String(length=500), nullable=False),
    sa.Column('c_fecha', sa.String(length=200), nullable=False),
    sa.Column('id_blog', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_blog'], ['blog.id_entrada'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('users')
    op.drop_table('blog')
    # ### end Alembic commands ###
