"""empty message

Revision ID: a00584501286
Revises: 
Create Date: 2020-05-05 20:37:40.963591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00584501286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.Column('e_titulo', sa.String(length=100), nullable=False),
    sa.Column('e_cuerpo', sa.String(length=500), nullable=False),
    sa.Column('e_cuerpopro', sa.String(length=1000), nullable=False),
    sa.Column('e_imagen', sa.String(length=250), nullable=True),
    sa.Column('e_fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_entrada')
    )
    op.create_table('tramites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('infointro', sa.String(length=1000), nullable=False),
    sa.Column('infocorps', sa.String(length=1000), nullable=False),
    sa.Column('infofoot', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('c_cuerpo', sa.String(length=500), nullable=False),
    sa.Column('c_fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tramitesusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareastramites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareastramitesusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramiteuser_id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tramiteuser_id'], ['tramitesusers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareastramitesusers')
    op.drop_table('tareastramites')
    op.drop_table('tramitesusers')
    op.drop_table('tareas')
    op.drop_table('comentarios')
    op.drop_table('users')
    op.drop_table('tramites')
    op.drop_table('blog')
    # ### end Alembic commands ###
