"""empty message

Revision ID: b772373ff0a1
Revises: 
Create Date: 2020-04-30 18:37:23.888179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b772373ff0a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('ta_id', sa.Integer(), nullable=False),
    sa.Column('task01', sa.String(length=100), nullable=False),
    sa.Column('task02', sa.String(length=100), nullable=True),
    sa.Column('task03', sa.String(length=100), nullable=True),
    sa.Column('task04', sa.String(length=100), nullable=True),
    sa.Column('task05', sa.String(length=100), nullable=True),
    sa.Column('task06', sa.String(length=100), nullable=True),
    sa.Column('task07', sa.String(length=100), nullable=True),
    sa.Column('task08', sa.String(length=100), nullable=True),
    sa.Column('task09', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ta_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('tramits',
    sa.Column('tr_id', sa.Integer(), nullable=False),
    sa.Column('tramit', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('ta_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ta_id'], ['tasks.ta_id'], ),
    sa.PrimaryKeyConstraint('tr_id'),
    sa.UniqueConstraint('tramit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tramits')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
